store/urls.py
from django.urls import path

from . import views

app_name = "store"

urlpatterns =[
    path("", views.Homepage , name = "index"),
    path("cart/", views.cart, name = "cart")
]

tarangafarms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("store.urls", namespace="store")),
    url("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField()
    image = models.ImageField(null = True, blank=True)
    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
        
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)  #many to one relationship which means a customer can have multiple orders
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default = False, null=True, blank=False) #changes the status oof the cart whether an open or closed cart 
    #transaction id if needed
    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total



#Order item will be like the items in the cart. cart can have multiple items so many to one relationship
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class DeliveryAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

store/views.py
from django.shortcuts import render
from .models import *
# Create your views here.

def Homepage(request):
    products = Product.objects.all()
    context = {'products': products}
    return render(request, "store/home.html", context)

def cart(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer = customer, complete = False)  #create an order or get an order if it exists
        items = order.orderitem_set.all()
    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0 } #incase the user is not logged in , temporarily setting it to false
    
    context = {'items':items, 'order':order}
    return render(request, "store/cart.html", context)
    

store/templates/store/cart.html
{% extends 'base.html' %}

{% block body %} 

<h2>Cart Total : {{order.get_cart_total}}</h2>
<h2>quantity: {{order.get_cart_items}}</h2>
<hr>
{% for item in items %}
    <img style="width: 100px; height: 100px" src="{{item.product.imageURL}}">
    <h1>{{item.product.name}}</h1>
    <h2>${{item.product.price}}</h2>
    <h3>quantity: {{item.quantity}}</h3>>
    <h3>total : ${{item.get_total}}</h3>
    <hr>
{% endfor %}

{% endblock %}

store/templates/store/home.html
{% extends "base.html" %}

{% block title %}Changed the title of the homepage{% endblock %}

{% block body %}
    {% for product in products %}
        <img style="width: 100px; height: 100px;" src="{{product.imageURL}}"><br>
        {{ product.name }} <br>
        price : {{ product.price}}<br>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">add to cart</button>
        <hr>
    {% endfor %}
{% endblock %}

tarangafarms/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Default title in here{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Taranga farms</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'store:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            
          </ul>>
          <a class="nav-link" href="{% url 'store:cart' %}">cart <span class="sr-only">(current)</span></a>
        </div>
      </nav>
    {% block body %}{% endblock %}
</body>
</html>